# Generated by Django 4.1.5 on 2023-10-24 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="ProductHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productname", models.CharField(blank=True, max_length=50, null=True)),
                ("quantity", models.IntegerField(blank=True, default="0", null=True)),
                (
                    "receive_quantity",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                ("receive_by", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "issue_quantity",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                ("issue_by", models.CharField(blank=True, max_length=50, null=True)),
                ("issue_to", models.CharField(blank=True, max_length=50, null=True)),
                ("updated", models.DateTimeField(null=True)),
                ("created", models.DateTimeField(null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated", "-created"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productname", models.CharField(max_length=200)),
                ("quantity", models.IntegerField(default="0")),
                ("receive_quantity", models.IntegerField(default="0", null=True)),
                ("receive_by", models.CharField(max_length=50)),
                ("issue_quantity", models.IntegerField(default="0", null=True)),
                ("issue_to", models.CharField(max_length=200)),
                ("issue_by", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to="myapp.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated", "-created"],
            },
        ),
    ]
